accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

doggy/urls.py
from django.urls import path
from . import views

app_name="doggy"

urlpatterns = [
    path('doggy_list/', views.doggy_list, name="doggy_list"),
    path('doggy_api/', views.doggy_api, name="doggy_api"),
]

post/urls.py
from django.urls import path
from . import views

app_name="post"

urlpatterns = [
	path('new/', views.new, name='new'),
	path('lists/', views.lists, name='lists'),
	path('<int:post_id>/', views.detail, name='detail'),
	path('create/', views.create, name='create'),
	path('<int:post_id>/edit/', views.edit, name='edit'),
	path('<int:post_id>/update/', views.update, name='update'),
	path('<int:post_id>/delete/', views.delete, name='delete'),
	path('<int:post_id>/create/comment', views.create_comment, name='create_comment'),
	path('<int:post_id>/like/', views.like, name='like'),
]

worklion/urls.py
from django.contrib import admin
from django.urls import path, include
from post import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('post/', include('post.urls')),
    path('accounts/', include('accounts.urls')),
    path('doggy/', include('doggy.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doggy/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    post_active = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    liked_users = models.ManyToManyField(User, related_name='liked_posts')
    post_image = models.ImageField(upload_to='post', null=True)

    def __str__(self):
        return f'{self.title}'


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth

def sign_up(request):
    if request.method == 'POST':
        if (request.POST['username'] and
                request.POST['password'] and
                request.POST['password'] == request.POST['password_check']):
            
            new_user = User.objects.create_user(
                username=request.POST['username'],
                password=request.POST['password'],
            )
            
            auth.login(request, new_user)
            return redirect('index')
    
    return render(request, 'sign_up.html')
    
def login(request):
    if request.method == 'POST':
        if request.POST['username'] and request.POST['password']:

            user = auth.authenticate(
                request,
                username=request.POST['username'],
                password=request.POST['password']
            )

            if user is not None:
                auth.login(request, user)
                return redirect('index')


    return render(request, 'login.html')
    
def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        
        
    return redirect('index')

doggy/views.py
from django.shortcuts import render, redirect
import requests
# Create your views here.

def doggy_list(request):
    return render(request, "doggy_list.html")

def doggy_api(request):
    base_url = 'https://dog.ceo/api/breed/'
    selection = request.POST['dog_selection']
    URL = base_url + selection + '/images/random'

    '''
    URL 연결이 잘 되었는지 확인하기 위해 print()를 사용하여 출력 해 봅니다. 
    print(URL)
    '''

    response = requests.get(URL)

    '''
    request로 올바른 상태값인 200이 나오는지 확인하고 우리가 적어준 요청대로 응답했는지 확인합니다.
    print(response.status_code)
    print(response.text)
    '''
    

    response_dictionary = response.json()
    dog = response_dictionary['message']

    return render(request, 'doggy_api.html', {'dog':dog})

post/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Post, Comment
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib.auth.decorators import login_required

# Create your views here.


def index(request):
    return render(request, 'index.html')


def new(request):
    return render(request, 'new.html')


def lists(request):
    post = Post.objects.all()
    context = {
        'post': post
    }
    return render(request, 'lists.html', context)


def detail(request, post_id):
    post = Post.objects.get(id=post_id)
    comments = Comment.objects.filter(post=post_id)
    context = {
        'post': post,
        'comments': comments
    }
    return render(request, 'detail.html', context)


def create(request):
    title = request.POST['title']
    content = request.POST['content']
    post_image = None
    if 'post_image' in request.FILES:
        post_image = request.FILES['post_image']
    post = Post(title=title, content=content, post_image=post_image, created_at=timezone.now())
    post.save()
    return redirect('post:detail', post_id=post.id)


def edit(request, post_id):
    post = Post.objects.get(id=post_id)
    context = {
        'post' : post
    }
    return render(request, 'edit.html', context)


def update(request, post_id):
    post = Post.objects.get(id=post_id)
    post.title = request.POST['title']
    post.content = request.POST['content']
    post.post_active = True
    post.save()
    return redirect('post:detail', post_id=post.id)


def delete(request, post_id):
    post = Post.objects.get(id=post_id)
    post.delete()
    return redirect('post:lists')


@login_required
def create_comment(request, post_id):
    user = request.user
    post_id = post_id
    content = request.POST['content']
    comment = Comment(user=user, post_id=post_id, content=content, created_at=timezone.now())
    comment.save()
    return redirect('post:detail', post_id=post_id)


@login_required
def like(request, post_id):
    if request.method == 'POST':
        try:
            post = Post.objects.get(id=post_id)
            
            if request.user in post.liked_users.all():
                post.liked_users.remove(request.user)
            else:
                post.liked_users.add(request.user)
            return redirect('post:detail', post.id)
        
        except Post.DoseNotExit:
            pass
    return redirect('post:index')

accounts/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Login</h1>
    <form method="POST" action="{% url 'accounts:login' %}">
    {% csrf_token %}
        <div class="form-group">
            <label for="exampleInputEmail1">아이디</label>
            <input type="text" class="form-control" id="exampleInputEmail1" name="username">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">비밀번호</label>
            <input type="password" class="form-control" id="exampleInputPassword1" name="password">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

accounts/templates/sign_up.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Sign_up</h1>
    <form method="POST" action="{% url 'accounts:sign_up' %}">
    {% csrf_token %}
        <div class="form-group">
            <label for="exampleInputEmail1">아이디</label>
            <input type="text" class="form-control" id="exampleInputEmail1" name="username">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">비밀번호</label>
            <input type="password" class="form-control" id="exampleInputPassword1" name="password">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">비밀번호 확인</label>
            <input type="password" class="form-control" id="exampleInputPassword1" name="password_check">
        </div>
        <button type="submit" class="btn btn-primary">회원가입</button>
    </form>
</div>
{% endblock %}

doggy/templates/doggy_api.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<div class="container">
    <h1>Dog API 활용하기 </h1>
    <div class="container">
    <img src="{{ dog }}">
    </div>
</div>
{% endblock %}

doggy/templates/doggy_list.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<div class="container">
    <h1>Dog API 활용하기 </h1>
    <div class="container">
    <form action="{% url 'doggy:doggy_api' %}" method="POST">
        {% csrf_token %}
        <select class="custom-select" name="dog_selection">
            <option selected>찾고 싶은 강아지를 골라주세요.</option>
            <option value="beagle">비글</option>
            <option value="borzoi">보르조이</option>
            <option value="collie">보더콜리</option>
            <option value="doberman">도베르만</option>
            <option value="husky">허스키</option>
        </select>
        <button type="submit" class="btn btn-primary btn-sm" style="float:right">Search</button>
    </form>
    </div>
</div>
{% endblock %}

post/templates/detail.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>View My Post</h1>
        <p>제목: {{ post.title }}</p>
        <p>내용: {{ post.content }}</p>
        {% if post.post_image %}
            <div class="container">
                <img src="{{ post.post_image.url }}" class="figure-img img-fluid rounded" width="50%" height="50%">
            </div>
        {% endif %}
        <p>게시일: {{ post.created_at }}</p>
        <br><br>
    좋아요 수 : {{ post.liked_users.count }}
    {% if user == post.user %}
<a href="{% url 'post:edit' post.id %}">글 수정하기</a>
<a href="{% url 'post:delete' post.id %}">글 삭제하기</a>
    {% endif %}

    {% if user.is_authenticated %}
        {% if user in post.liked_users.all %}
            <form action="{% url 'post:like' post.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">
                    Unlike
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-suit-heart" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M8 6.236l.894-1.789c.222-.443.607-1.08 1.152-1.595C10.582 2.345 11.224 2 12 2c1.676 0 3 1.326 3 2.92 0 1.211-.554 2.066-1.868 3.37-.337.334-.721.695-1.146 1.093C10.878 10.423 9.5 11.717 8 13.447c-1.5-1.73-2.878-3.024-3.986-4.064-.425-.398-.81-.76-1.146-1.093C1.554 6.986 1 6.131 1 4.92 1 3.326 2.324 2 4 2c.776 0 1.418.345 1.954.852.545.515.93 1.152 1.152 1.595L8 6.236zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z"/>
                    </svg>
                </button>
            </form>
        {% else %}
            <form action="{% url 'post:like' post.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">
                    Like
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-suit-heart-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                      <path d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z"/>
                    </svg>
                </button>
            </form>
        {% endif %}
    {% endif %}

</div>

<br>
{% if user.is_authenticated %}
<div class="container">
    <form action="{% url 'post:create_comment' post.id %}" method="POST">
    {% csrf_token %}
        <div class="form-group">
            <textarea class="form-control" rows="3" placeholder="내용을 적어주세요." name="content"></textarea>
        </div>
        <input type="hidden" value="{{ post.id }}" name="post_id">
        <button type="submit" class="btn btn-secondary btn-sm" style="float:right">글 작성하기</button>
    </form>
</div>
{% endif %}
<br>
<br>
<br>
<div class="container">
{% for comment in comments %}
    <div class="card">
        <div class="card-body">
            <p>작성자: {{comment.user.get_username}}</p>
            <p>{{comment.content}}</p>
            <p style="float:right;">{{comment.created_at}}</p>
        </div>
    </div>
{% endfor %}
</div>
{% endblock %}

post/templates/edit.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>Write Post</h1>
    <div class="container">
        <form action="{% url 'post:update' post.id %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <input class="form-control" type="text" placeholder="제목을 적어주세요." name="title" value="{{ post.title }}">
            </div>
            <div class="form-group">
                <textarea class="form-control" rows="3" placeholder="내용을 적어주세요." name="content">{{ post.content }}</textarea>
            </div>
            <button type="submit" class="btn btn-secondary btn-sm" style="float:right">글 작성하기</button>
        </form>
    </div>
</div>    
{% endblock %}

post/templates/index.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<div class="container">
    <h1>HELLO WORKSLION!</h1>
    <p>우리는 멋쟁이 사-자</p>
    <img src="{% static 'image/lion.jpg' %}">
</div>
{% endblock %}

post/templates/lists.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">This is my list page!</h1>
        <hr class="my-4">
        {% for post in post %}
            {% if post.post_active == True %}
            <a href="{% url 'post:detail' post.id %}"><p class="lead">{{ post.title }}</p></a>
            {% endif%}
        {% endfor %}
    </div>
</div>
{% endblock %}

post/templates/new.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>Write Post</h1>
    <div class="container">
        <form action="{% url 'post:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
            <div class="form-group">
                <input class="form-control" type="text" placeholder="제목을 적어주세요." name="title">
            </div>
            <div class="form-group">
                <textarea class="form-control" rows="3" placeholder="내용을 적어주세요." name="content"></textarea>
            </div>
            <div class="form-group">
                <label for="exampleFormControlFile1">이미지를 넣어주세요.</label>
                <input type="file" class="form-control-file" id="exampleFormControlFile1" name="post_image">
            </div>
            <button type="submit" class="btn btn-secondary btn-sm" style="float:right">글 작성하기</button>
        </form>
    </div>
</div>
{% endblock %}    

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>worklion</title>
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</head>
<body>
    {% load static %}
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'index' %}">WORKSLION</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" href="{% url 'post:lists' %}">lists</a>
                    <a class="nav-link active" href="{% url 'doggy:doggy_list' %}">doggy</a>
                    {% if user.is_authenticated %}
                        <form action="{% url 'accounts:logout' %}" method="POST" class="form-inline">
                            {% csrf_token %}
                            {{ user.get_username }}
                            <a class="nav-link active" href="{% url 'post:new' %}">new</span></a>
                            <button type="submit" class="btn btn-primary">로그아웃</button>
                        </form>
                    {% else %}
                        <a class="nav-link active" href="{% url 'accounts:login' %}">로그인</span></a>
                        <a class="nav-link active" href="{% url 'accounts:sign_up' %}">회원가입</span></a>
                    {% endif %}
                </div>
            </div>
        </nav>
    
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>